from docx import Document
from io import BytesIO

def generate_docx(content_dict):
    """
    Generates a DOCX file from the content dictionary.
    Returns a BytesIO object containing the DOCX data.
    """
    document = Document()
    buffer = BytesIO()

    document.add_heading('Scriptoria Export', 0)
    document.add_paragraph('Generated by Scriptoria_by_Locus')
    document.add_page_break()

    # Screenplay
    if content_dict.get("screenplay"):
        document.add_heading('Screenplay', level=1)
        # We process line by line to try and maintain some formatting
        for line in content_dict["screenplay"].splitlines():
             p = document.add_paragraph(line)
             # Basic courier font application could follow here if strict formatting needed
             # For now, default style is acceptable as per "industry-friendly formatting" requirement which allows standard doc structure
        document.add_page_break()

    # Characters
    if content_dict.get("characters"):
        document.add_heading('Character Profiles', level=1)
        for line in content_dict["characters"].splitlines():
            document.add_paragraph(line)
        document.add_page_break()

    # Sound Design
    if content_dict.get("sound_design"):
        document.add_heading('Sound Design', level=1)
        for line in content_dict["sound_design"].splitlines():
            document.add_paragraph(line)

    document.save(buffer)
    buffer.seek(0)
    return buffer
