from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO

def generate_pdf(content_dict):
    """
    Generates a PDF from the content dictionary.
    Returns a BytesIO object containing the PDF data.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Screenplay', fontName='Courier', fontSize=12, leading=14, spaceAfter=12))
    styles.add(ParagraphStyle(name='CenterTitle', parent=styles['Heading1'], alignment=TA_CENTER, spaceAfter=24))

    story = []

    # Title Page
    story.append(Paragraph("Scriptoria Export", styles['CenterTitle']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by Scriptoria_by_Locus", styles['BodyText']))
    story.append(PageBreak())

    # Screenplay Section
    if content_dict.get("screenplay"):
        story.append(Paragraph("Screenplay", styles['Heading2']))
        story.append(Spacer(1, 12))
        # Handle newlines by splitting and creating paragraphs to preserve formatting
        for line in content_dict["screenplay"].splitlines():
            if not line.strip():
                story.append(Spacer(1, 12))
            else:
                # Replace spaces for indentation (approximate for now)
                clean_line = line.replace(" ", "&nbsp;")
                story.append(Paragraph(clean_line, styles['Screenplay']))
        story.append(PageBreak())

    # Characters Section
    if content_dict.get("characters"):
        story.append(Paragraph("Character Profiles", styles['Heading2']))
        story.append(Spacer(1, 12))
        for line in content_dict["characters"].splitlines():
             if not line.strip():
                story.append(Spacer(1, 12))
             else:
                story.append(Paragraph(line, styles['BodyText']))
        story.append(PageBreak())

    # Sound Design Section
    if content_dict.get("sound_design"):
        story.append(Paragraph("Sound Design", styles['Heading2']))
        story.append(Spacer(1, 12))
        for line in content_dict["sound_design"].splitlines():
             if not line.strip():
                story.append(Spacer(1, 12))
             else:
                story.append(Paragraph(line, styles['BodyText']))

    doc.build(story)
    buffer.seek(0)
    return buffer
